=== rheinmainrocks/ugrm-data/xsd/usergroup.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="usergroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string">
					<xs:annotation>
						<xs:documentation>Vollständiger Name der Usergroup in Langfassung,
							z.B. Python UserGroup RheinMain
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="nickname" type="xs:string">
					<xs:annotation>
						<xs:documentation>Kurzform des Usergroup-Namens, z.B. PyUGRM
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="description" type="xs:string">
					<xs:annotation>
						<xs:documentation>Eine Beschreibung der Usergroup. Kann gerne
							ausführlich sein.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="url" type="xs:anyURI">
					<xs:annotation>
						<xs:documentation>Die URL der Homepage der Usergroup.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="contact">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mailinglist" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="url" type="xs:anyURI"></xs:element>
										<xs:element name="label" type="xs:string"></xs:element>
										<xs:element name="description" type="xs:string"
											minOccurs="0"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="twitter" minOccurs="0" type="twitter"></xs:element>
							<xs:element name="hashtag" minOccurs="0" type="hashtag"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ical" minOccurs="0" type="xs:anyURI"></xs:element>
				<xs:element name="schedule">
					<xs:complexType>
						<xs:annotation>
							<xs:documentation>Liefert Information zu den nächsten Treffen der
								UserGroup. Entweder kann die URL zu einem iCal-Feed angegeben
								werden, oder die Meetings werden manuell konfiguriert.
							</xs:documentation>
						</xs:annotation>
						<xs:choice>
							<xs:element name="ical" type="xs:anyURI"></xs:element>
							<xs:element name="meeting" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:dateTime"></xs:element>
										<xs:element name="location" type="xs:string"></xs:element>
										<xs:element name="description" type="xs:string"
											minOccurs="0"></xs:element>
										<xs:element name="publictransport" type="xs:string"
											minOccurs="0"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="tags">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tag" type="xs:token" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="photocredits" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="logo" type="xs:string" minOccurs="0"></xs:element>
							<xs:element name="group" type="xs:string" minOccurs="0"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sponsors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sponsor" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string"></xs:element>
										<xs:element name="url" type="xs:anyURI"></xs:element>
										<xs:element name="city" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="meetings" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Links zu den Infoseiten oder Protokollen
							vergangener Treffen.
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="meeting" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:date"></xs:element>
										<xs:element name="url" type="xs:anyURI"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="twitter">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentype für Twitter-Handles
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="@[a-zA-Z0-9_]{1,15}"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="hashtag">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentype für Hashtags
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="#[a-zA-Z0-9]+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== rheinmainrocks/ugrm-data/usergroup/donnerstalk.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>Donnerstalk im Heimathafen Wiesbaden</name>
    <description>
        Der Donnerstalk ist ein angeregter Austausch zwischen sympathischen Leuten aus der Region in entspannter
        Atmosphäre, bei dem Wissenstransfer und Networking auf gelungene Weise kombiniert werden.
    </description>
    <url>http://heimathafen-wiesbaden.de/category/donnerstalk/</url>
    <tags>
        <tag>Talk</tag>
        <tag>Idea</tag>
        <tag>Beer</tag>
    </tags>
    <contact>
        <hashtag>#donnerstalk</hashtag>
    </contact>
    <defaultmeetinglocation>
        <name>heimathafen Wiesbaden</name>
        <description>Der heimathafen Wiesbaden ist ein Coworking Space &amp; Café. Wir vermieten Arbeitsplätze an
            Kreative &amp; Selbständige, Konferenzräume an Firmen &amp; Agenturen - und verkaufen Kaffee an jedermann.
        </description>
        <url>http://heimathafen-wiesbaden.de/</url>
        <foursquare>https://de.foursquare.com/heimathafenwi</foursquare>
        <twitter>@heimathafenWI</twitter>
        <publictransport>Hauptbahnhof Wiesbaden</publictransport>
        <street>Karlstraße 22 (Adelheidstraße)</street>
        <zip>65185</zip>
        <city>Wiesbaden</city>
    </defaultmeetinglocation>
    <schedule usedefaultmeetinglocation="true">
        <meeting>
            <time>2013-11-07T19:00:00+01:00</time>
            <name>Donnerstalk im November: FUTURE OF WORK</name>
            <description>
                Der Donnerstalk im November wird ein Highlight der noch jungen Donnerstalk-Geschichte: Ein
                hochspannendes Thema - und zwei vielversprechende Speaker: THE FUTURE OF WORK.

                **DAS ENDE DER ARBEIT**
                Wenn Maschinen uns ersetzen
                *Johannes Kleske, Co-Founder [ThirdWaveBerlin](http://thirdwaveberlin.com/)*

                Dieser Vortrag hat schon auf der re:publica
                2013 für Aufsehen gesorgt: Jobs, die bis vor wenigen Jahren noch als sicher galten, können heute von
                Algorithmen ausgeführt werden. Maschinen übernehmen mehr Arbeit als wir gerade neue schaffen können. Das
                stellt uns vor die Frage, wie wir eigentlich in Zukunft leben wollen: als Sklaven der Maschinen oder in
                einem neuen, „digitalen Athen“?


                **THE FUTURE OF WORK**
                Von Human Ressources zu Ressourceful Humans
                Heiko Fischer, Gründer [Ressourceful Humans](http://www.resourceful-humans.de/)

                Was ist der Sinn und Zweck einer wirtschaftlichen Organisation
                – Profit, Sinnstiftung, Imagevermehrung, Kunden glücklich machen? Firmen müssen genügend Geld
                erwirtschaften und Produkte erschaffen, ohne die ihre Kunden etwas vermissen würden. Gute Produkte –
                geschaffen von Menschen, die Spaß daran haben, sie zu kreieren. Doch wie funktioniert die Balance
                zwischen ‘Wollen’ und kreativem Schaffen einerseits und ‘Müssen’ und wirtschaftlichem Druck
                andererseits?

                Der Möglichmacher des Abends, aka Sponsor, liefert gleich selbst das beste Beispiel für den radikalen
                Versuch eines Neuanfangs in der Arbeitswelt: essquare - we help build organizations of the future
                by building products for today. http://www.essquare.de/

                Die Vorträge beginnen gegen 19:00 Uhr - die meisten kommen allerdings früher und genießen einen
                Feierabend-Drink in unserem Café. Nach den Vorträgen wie immer: Feierabendbier (für Durstige) und
                lockeres Netzwerken (für Jedermann).

                Achtung, Achtung: Bitte über Facebook oder [XING](https://www.xing.com/events/donnerstalk-november-future-of-work-1314977) anmelden!
            </description>
            <url>https://www.xing.com/events/donnerstalk-november-future-of-work-1314977</url>
        </meeting>
        <meeting>
            <time>2013-10-02T18:30:00+02:00</time>
            <name>Mittwochs-Donnerstalk zum Thema BIG DATA</name>
            <description>Snowden, NSA, Prism – die große Datensammelwut ist längst Realität. Doch: Hat sie auch ihr
                Gutes? Wie kann BIG DATA uns helfen, unsere Produkte, User Experience und Services besser zu machen?
                Und: Was genau meint BIG DATA eigentlich? Um diese und andere Fragen dreht sich der Donnerstalk im
                Oktober – diesmal mit einem absoluten Novum: Donnerstalk ist das erste Mal an einem Mittwoch – immerhin
                wollen wir alle am 03.10. frei haben (dem Tag der deutschen Einheit, an dem unser Café geöffnet sein
                wird). Der Vortrag lautet: BIG DATA: Zaubertrank für Staaten &amp; Unternehmen, Teufelszeug für Bürger
                &amp;
                Kunden?

                Infos und Anmeldung, wie immer, unter http://facebook.com/heimathafenwiesbaden/events
            </description>
            <url>
                http://heimathafen-wiesbaden.de/2013/09/30/premiere-mittwochs-donnerstalk-zum-thema-big-data-am-02-10/
            </url>
        </meeting>
        <meeting>
            <time>2013-09-05T18:30:00+02:00</time>
            <name>Donnerstalk im September: „Entfalte dein (kreatives) Potential!“</name>
            <description>Welches sind die größten Kreativitätskiller und wann schlagen diese in der Regel zu? Wie viel
                von unserem (kreativen) Potential leben wir überhaupt aus? Und wie sehr entfalten sich eigentlich
                „Kreative“ – oder gibt’s da auch noch Luft nach oben? Der Impulsvortrag hat nicht nur Antworten und Mut
                machen auf Lager. Neben einem ordentlichen Perspektivwechsel wird kräftig reflektiert, um am Ende sagen
                zu können, „Wow, da steckt wohl auch in mir noch viel mehr, als mir vermeintlich bewusst ist…! Denk- und
                Umdenkanstöße inklusive.
            </description>
            <url>https://www.xing.com/events/donnerstalk-september-entfalte-kreatives-potential-1281242</url>
        </meeting>
        <meeting>
            <time>2013-08-01T18:30:00+02:00</time>
            <name>Donnerstalk plus 1 Jahr heimathafen-Feier am 01. August</name>
            <description>
                Das Thema im August: "Design (your) Thinking"
                Design Thinking ist eine Art Kreativ-Methode, mit der sich innerhalb kurzer Zeit kreative Ideen &amp;
                innovative Lösungen entwickeln lassen. Wir lernen den strukturierten, interdisziplinären Prozess des
                Design Thinking kennen &amp; wenden ihn im konkreten Fall an. Mehr Kreativität? Mehr Innovation? Design
                (your) Thinking!

                Für den Donnerstalk ist die Anmeldung über XING ist notwendig.
            </description>
            <url>https://www.xing.com/events/donnerstalkplus-design-your-thinking-1-heimathafen-feier-1279534</url>
        </meeting>
    </schedule>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/tuxcamp.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           female="false">
    <name>TuXCamp – Das Linux-BarCamp</name>
    <nickname>TuXCamp</nickname>
    <description>Das TuXCamp ist ein BarCamp auf dem es vor allem um das freie Betriebssystem Linux geht; es richtet
        sich dabei besondes an Schüler und Studenten um diese schon früh mit der OpenSource-Bewegung in Kontakt zu
        bringen.</description>
    <url>http://rhscamp.mixxt.de/</url>
    <tags>
        <tag>BarCamp</tag>
        <tag>Linux</tag>
        <tag>Open Source</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2013-09-28T09:00:00+02:00</time>
            <name>TuXCamp 2013 – Freiheit und Sicherheit im Netz</name>
            <description><![CDATA[Warum OpenSource? Warum GNU/Linux? Warum an der Schule? Wir laden die Communities ein und geben Antwort auf dem TuxCamp 2013! Für Catering und Übernachtungsmöglichkeit von Freitag auf Samstag wird gesorgt werden.

            Vorträge & Sessions
            -----------------------

            * Einführung in die Arbeit mit GNU/Linux für Anfänger
            * Linux Essentials (LPI)
            * Live-Hacking (noch nicht sicher)
            * Eine Distribution selbst erstellen - wie geht das?
            * Programmieren unter Linux
            * Einführung in TeX (wofür kann man das gebrauchen?)
            * Vorbereitung auf die Arbeit an der Universität (Welche Tools sind hilfreich?)
            * Vorbereitung auf die berufliche Bewerbung mithilfe von OpenSource-Plattformen
            * ... und vieles mehr.

            Am Vorabend findet eine [Installations-Party](http://rhscamp.mixxt.de/networks/events/show_event.81063) statt.
            ]]></description>
            <url>http://rhscamp.mixxt.de/networks/events/show_event.81064</url>
            <location>
                <name>Ricarda-Huch-Schule</name>
                <url>http://ricarda-huch.dreieich.schule.hessen.de/</url>
                <street>Breslauer Str. 15-25</street>
                <zip>63303</zip>
                <city>Dreieich - Sprendlingen</city>
            </location>
        </meeting>
    </schedule>
    <photocredits>
        <logo>Logo: [rhscamp.mixxt.de](http://rhscamp.mixxt.de/)</logo>
    </photocredits>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/pm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Frankfurt Perl Mongers</name>
    <nickname>Frankfurt.pm</nickname>
    <description>Frankfurt Perl Mongers sind Menschen, die sich mit der dynamischen Programmiersprache Perl beschäftigen
        und gerne darüber reden.

        Wir treffen uns seit dem Jahr 2000 ein Mal im Monat in lockerer Atmosphäre. Der
        Schwerpunkt ist natürlich Perl, dennoch widmen wir uns auch Randgebieten und auch schon mal anderen
        Programmiersprachen.

        Wir richten uns an alle, die das Interesse haben, etwas mit Perl zu machen. Dabei spielt keine Rolle, ob
        beruflich oder nur als "Hobby". Jeder ist willkommen, der auch nur einen Funken Interesse am Programmieren mit
        Perl hat.
    </description>
    <url>http://frankfurt.pm.org/</url>
    <tags>
        <tag>Perl</tag>
    </tags>
    <contact>
        <mailinglist>
            <url>http://mail.pm.org/mailman/listinfo/frankfurt-pm?language=de</url>
            <label>Mailingliste (deutsch)</label>
            <description>Such Dir aus, ob Du auf deutsch (auch hessisch wenns denn sein soll) oder englisch schreibst
                (auch kleinere Mengen Perl Code sind ganz ok), und erlaube Anderen in der Sprache zu antworten, in der
                es ihnen zu antworten gefällt.
            </description>
        </mailinglist>
        <mailinglist>
            <url>http://mail.pm.org/mailman/listinfo/frankfurt-pm?language=en</url>
            <label>Frankfurt/Main Perl Mongers Mailing List (English)</label>
            <description>Feel free to write either in English or in German (Hessian if you prefer) or post small amounts
                of Perl code there and ask for opinions. Allow others to reply in the language they prefer to reply in.
            </description>
        </mailinglist>
    </contact>
</usergroup>
