=== rheinmainrocks/ugrm-data/xsd/usergroup.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="usergroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string">
					<xs:annotation>
						<xs:documentation>Vollständiger Name der Usergroup in Langfassung,
							z.B. Python UserGroup RheinMain
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="nickname" type="xs:string">
					<xs:annotation>
						<xs:documentation>Kurzform des Usergroup-Namens, z.B. PyUGRM
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="description" type="xs:string">
					<xs:annotation>
						<xs:documentation>Eine Beschreibung der Usergroup. Kann gerne
							ausführlich sein.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="url" type="xs:anyURI">
					<xs:annotation>
						<xs:documentation>Die URL der Homepage der Usergroup.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="contact">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mailinglist" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="url" type="xs:anyURI"></xs:element>
										<xs:element name="label" type="xs:string"></xs:element>
										<xs:element name="description" type="xs:string"
											minOccurs="0"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="twitter" minOccurs="0" type="twitter"></xs:element>
							<xs:element name="hashtag" minOccurs="0" type="hashtag"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ical" minOccurs="0" type="xs:anyURI"></xs:element>
				<xs:element name="schedule">
					<xs:complexType>
						<xs:annotation>
							<xs:documentation>Liefert Information zu den nächsten Treffen der
								UserGroup. Entweder kann die URL zu einem iCal-Feed angegeben
								werden, oder die Meetings werden manuell konfiguriert.
							</xs:documentation>
						</xs:annotation>
						<xs:choice>
							<xs:element name="ical" type="xs:anyURI"></xs:element>
							<xs:element name="meeting" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:dateTime"></xs:element>
										<xs:element name="location" type="xs:string"></xs:element>
										<xs:element name="description" type="xs:string"
											minOccurs="0"></xs:element>
										<xs:element name="publictransport" type="xs:string"
											minOccurs="0"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="tags">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tag" type="xs:token" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="photocredits" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="logo" type="xs:string" minOccurs="0"></xs:element>
							<xs:element name="group" type="xs:string" minOccurs="0"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sponsors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sponsor" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string"></xs:element>
										<xs:element name="url" type="xs:anyURI"></xs:element>
										<xs:element name="city" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="meetings" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Links zu den Infoseiten oder Protokollen
							vergangener Treffen.
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="meeting" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:date"></xs:element>
										<xs:element name="url" type="xs:anyURI"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="twitter">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentype für Twitter-Handles
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="@[a-zA-Z0-9_]{1,15}"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="hashtag">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentype für Hashtags
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="#[a-zA-Z0-9]+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== rheinmainrocks/ugrm-data/usergroup/dnugffm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>.NET User Group Frankfurt/Main</name>
    <nickname>DNUGFFM</nickname>
    <description>Die .NET User Group Frankfurt/Main beschäftig sich als freie, unabhängige und heterogene Gruppe mit der
        .NET-Programmierung im Allgemeinen aber auch mit Produkten und Tools, die in diesem Umfeld existieren.

        Im Vordergrund steht dabei der Austausch von technologischem Wissen und Erfahrungen. Diesen Know-How Transfer
        versuchen wir in monatlichen Meetings, mit Vorträgen von Mitgliedern und namhaften Sprechern sowie mit
        Diskussionen, zu realisieren.

        Da bei uns jede .NET Programmiersprache (C#, VB.NET, IronPython, Powershell, etc.) sowie .NET Implementierung
        (z.B Rotor, Mono) willkommen ist, sind wir auch offen für alles im .NET-Universum und laden alle Interessierten
        dazu ein, Mitglied dieser Benutzergruppe zu werden.
    </description>
    <url>http://www.dotnet-usergroup.de/</url>
    <tags>
        <tag>.NET</tag>
        <tag>C#</tag>
		<tag>Microsoft</tag>
    </tags>
    <contact>
        <twitter>@dnugffm</twitter>
    </contact>
	   <defaultmeetinglocation>
        <name>Microsoft Deutschland GmbH (Geschäftsstelle Bad Homburg)</name>
        <url>https://www.microsoft.com/de-de/corporate/ueber-uns/standorte-directions.aspx</url>
        <street>Siemensstraße 27</street>
        <zip>61352</zip>
        <city>Bad Homburg</city>
    </defaultmeetinglocation>
    <schedule usedefaultmeetinglocation="true">
        <meeting>
            <time>2014-01-16T18:30:00+01:00</time>
            <name>.NET User Group Meeting - Von Null über Werbung zum Windows Store</name>
			<description>			
Wie starte ich am besten mit der Entwicklung von Windows 8 Apps? Was ist der Weg, um über Werbung in meiner App Geld zu verdienen? Wie bekomme ich meine App in den Windows Store und was passiert dann?

Diese Fragen hat sich Stefan im Sommer 2013 gestellt. In dem Vortrag schildert er seine Erfahrungen vom Erstellen der ersten App über die Nutzung von Werbung bis zum Management im Windows Store. Er geht sowohl auf technische Aspekte und Unterschiede zur "klassischen" Entwicklung von .NET Anwendungen ein als auch auf das Management von Werbung und Windows Store.

Der Vortrag richtet sich an alle, die an der Entwicklung und Veröffentlichung von Windows 8 Apps interessiert sind, selbst aber noch keine Gelegenheit dazu hatten. Natürlich sind auch erfahrene Zuhörer willkommen, die eingeladen sind, mit Ihren Diskussionsbeiträgen das Bild zu ergänzen. Am Ende des Vortrags steht eine umfangreiche Linksammlung zu den angesprochenen Punkten.

Wir freuen uns, dass wir mit Stefan mal wieder einen Sprecher aus unserer User Group mit einem Vortrag bei uns begrüßen dürfen. Sicher wird dies ein interessanter und unterhaltsamer Abend.

Im Anschluss an den Vortrag geht es dann wie gewohnt zum Networking ins Brauhaus. Dort gibt es bei einem kühlen Getränk und leckeren Speisen die Gelegenheit für vertiefende Gespräche und weiteren Austausch.
            </description>
            <url>http://www.dnug-frankfurt.de/Event/tabid/119/ID/81/Default.aspx</url>
        </meeting>
    </schedule>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/agilerstammtischffm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Agiler Stammtisch Frankfurt</name>
    <description>
		Sie sind Entwickler oder Projektleiter im IT-Bereich und möchten sich gern mit 
		Gleichgesinnten über agiles Testen, agile Entwicklung, agiles Projektmanagement 
		oder einfach Agilität im Allgemeinen austauschen? Dann sind Sie beim Agilen Stammtisch 
		der1. Agilen Stammtisch Frankfurt - Marketing Nachricht codecentric AG genau richtig!
		In entspannter Atmosphäre können knifflige Probleme aus Ihrem beruflichen Alltag mit 
		Gleichgesinnten besprochen werden und natürlich wollen wir auch gegenseitig 
		Erfahrungen und Best Practices austauschen.
    </description>
    <url/>
    <tags>
        <tag>Agile</tag>
        <tag>Scrum</tag>
        <tag>Kanban</tag>
    </tags>
    <contact>
        <hashtag>#agileFFM</hashtag>
    </contact>
    <schedule>
        <meeting>
            <time>2013-06-13T18:30:00+02:00</time>
            <name>1. Agiler Stammtisch Frankfurt</name>
            <description>
                Nach einem kurzen Vortrag als Impuls setzen wir den Stammtisch in einen
                Lean-Kaffee Format (www.leancoffee.org) fort, welches Diskussionen rund um alle
                wichtigen Themen der Agilität fördert. Das Format lebt von den Teilnehmern,
                Sie sind also herzlich eingeladen, Ihre eigenen Themen mitzubringen.
                Das Schwerpunktthema des Abends werden Retrospektiven sein.
                Getränke werden von codecentric AG gesponsort.
            </description>
			<url>https://www.xing.com/events/1-agiler-stammtisch-frankfurt-1252844</url>
            <location>
                <name>Die Zentrale</name>
                <street>Berger Straße 175</street>
                <zip>60385</zip>
                <city>Frankfurt</city>
            </location>

        </meeting>
    </schedule>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/webgrrls.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>webgrrls Rhein-Main</name>
    <description>webgrrls ist das Netzwerk für weibliche Fach- und Führungskräfte, die in oder für Neue Medien arbeiten.
        First give, then take - nach diesem Motto fördern die webgrrls die berufliche Weiterentwicklung, die Präsenz und
        den Einfluss von Frauen innerhalb ihrer Branche.
    </description>
    <url>http://www.webgrrls-rheinmain.de/</url>
    <tags>
        <tag>Internet</tag>
    </tags>
    <contact>
        <twitter>@webgrrls_rm</twitter>
    </contact>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/devops.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd"
           plural="true">
    <name>DevOps Frankfurt</name>
    <description>Wir tauschen Erfahrungen und Best Practices aus, die wir beim Integrieren von Continuous Integration,
        Continuous Deployment, Configuration Management, Agilen Methoden etc. im eigenen Arbeitsalltag gesammelt haben.
        Du bist hier richtig, wenn Du Spaß an Automatisierung bei der Qualitätsicherung und beim Server-Management hast.
        Entwickler und Systemadministratoren sind gleichermaßen sehr willkommen, um Erfahrungen auszutauschen und
        voneinander zu lernen. Die Talks sind auf deutsch oder english. --- Learn more about and share information on
        the DevOps movement - culture, practices and tools. This is a group for professionals (and hackers), managers,
        and engineers - from dev or ops backgrounds - that are eager to learn more about automation tools. We meet every
        second month to discuss all things DevOps. Each meeting will include a speaker on any DevOps related topic, a Q&amp;A
        session followed by drinks. We speak German and English :)
    </description>
    <url>http://www.meetup.com/DevOps-Frankfurt/</url>
    <tags>
        <tag>DevOps</tag>
    </tags>
    <schedule>
        <!-- Entweder ical-Feed angeben oder Meetings manuell eintragen -->
        <!-- ical> https://www.google.com/calendar/ical/q408a75de70rb2ebqka3i18nc0%40group.calendar.google.com/public/basic.ics
            </ical -->
        <meeting>
            <time>2013-04-17T19:00:00+02:00</time>
            <name>2. Treffen der DevOps FFM</name>
            <url>http://www.meetup.com/DevOps-Frankfurt/events/109294502/</url>
        </meeting>
    </schedule>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/igd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd" incubator="true">
    <name>Independent Game Developers Rhein-Main</name>
    <description>This group is for everyone in the Rhein-Main area who is interested in game development and would like
        to exchange with other developers and game designers. The goal is to meet once a month, get to know each other
        and talk about various topics, e.g. frameworks and tools, marketing your game, monetization or just the love for
        game development.
    </description>
    <url>http://www.meetup.com/Independent-Game-Developers-Rhein-Main-Meetup</url>
    <tags>
        <tag>Game Development</tag>
        <tag>Programming</tag>
        <tag>Indie Games</tag>
    </tags>
    <team>
        <person>
            <name>Ali Banani</name>
            <url>http://banani.de/</url>
            <twitter>@AliBanani</twitter>
        </person>
    </team>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/smffm.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd" female="false">
    <name>Social Media Stammtisch Frankfurt</name>
    <nickname>SM/FFM</nickname>
    <description>Neuste Trends und Erfahrungen um das Social Web werden ausgetauscht und wirtschaftlich, kulturell oder
        auch philosophisch durchleuchtet. Alles eben, was den Social Media Profi interessiert. Ab und an werden
        Impulsvorträge gehalten. Beim Social Media Stammtisch Frankfurt geht es seit April 2010 regelmäßig um neuste
        Trends und Erfahrungen um das Social Web. Dabei werden wir das Thema möglichst breit diskutieren;
        Wirtschaftlich, kulturell oder auch philosophisch. Alles eben, was den Social Media Profi interessiert. Ab und
        an werden Impulsvorträge gehalten.
    </description>
    <url>https://www.facebook.com/socialmediafrankfurt</url>
    <tags>
        <tag>Social Media</tag>
    </tags>
    <contact>
        <googleplus>https://plus.google.com/102599953080163884985/posts</googleplus>
    </contact>
    <schedule>
        <!-- Entweder ical-Feed angeben oder Meetings manuell eintragen -->
        <!-- ical> https://www.google.com/calendar/ical/q408a75de70rb2ebqka3i18nc0%40group.calendar.google.com/public/basic.ics
            </ical -->
        <meeting>
            <time>2013-02-12T19:00:00+01:00</time>
            <name>Social Media Stammtisch #10</name>
            <url>https://www.facebook.com/events/202079356600101/</url>
            <location>
                <name>Die Zentrale</name>
                <description>Coworking in Frankfurt. Echt jetzt. Nein, wirklich. Wir sind kein Business
                    Center. Wir haben nicht nur Schreibtische und Wlan zu vermieten.
                </description>
                <url>http://www.die-zentrale-ffm.de/#section-n6</url>
                <twitter>@zentrale_ffm</twitter>
                <publictransport>U4, Tram 12, Bus 34 Bornheim Mitte</publictransport>
                <street>Berger Straße 175</street>
                <zip>60385</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
    </schedule>
    <photocredits>
        <logo>Logo: [Facebook](https://www.facebook.com/socialmediafrankfurt).</logo>
    </photocredits>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/lwsrm.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd" incubator="true">
    <name>Limited WIP Society Rhein-Main</name>
    <nickname>LWSRM</nickname>
    <description>Eine Kanban Usergroup für die Rhein-Main Region</description>
    <url>https://www.xing.com/net/lwsrm</url>
    <tags>
        <tag>Kanban</tag>
    </tags>
    <contact>
        <hashtag>#lwsrm</hashtag>
    </contact>
    <team>
        <person>
            <name>Kurt Häusler</name>
            <url>https://www.xing.com/profile/Kurt_Haeusler2</url>
            <email>kurt.haeusler@gmail.com</email>
            <twitter>@Kurt_Haeusler</twitter>
        </person>
    </team>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/hugrheinmain.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Hadoop User Group Rhein-Main</name>
    <nickname>HUG Rhein-Main</nickname>
    <description>Interessiert an Apache Hadoop und dem Ökosystem (Pig, Hive, HBase, 
  	HCatalog, Ambari, ...)? Oder schon Erfahrung mit Hadoop gesammelt? Oder sogar 
		ein Hadoop-Ninja? Und dazu noch in der schönen Rhein-Main-Region unterwegs? 
		Dann ist diese Gruppe genau der richtige Ort, um andere Hadoop-Verrückte 
		kennenzulernen, mehr über Hadoop zu lernen, inspirierende Vortrag anzuhören, mit 
		großartigen Menschen zu diskutieren und zusammen eine lebendige Community zu 
		bilden. Wir werden uns regelmäßig alle zwei Monate an verschiedenen Locations in 
		in der Rhein-Main-Region treffen. Falls du Interesse daran hast ein zukünftiges 
		Treffen zu hosten oder einen Vortrag halten willst, gib uns bitte einfach kurz 
		Bescheid...
    </description>
    <url>http://www.meetup.com/HUG-Rhein-Main/</url>
    <tags>
        <tag>Hadoop</tag>
        <tag>Big Data</tag>
		<tag>Pig</tag>
		<tag>Hive</tag>
		<tag>HBase</tag>
		<tag>HCatalog</tag>
		<tag>Ambari</tag>
    </tags>
    <contact>
        <twitter>@uweseiler</twitter>
        <hashtag>#HUGRM</hashtag>
        <team>
            <person>
                <name>Uwe Seiler</name>
                <email>uwe.seiler@gmail.com</email>
            </person>
            <person>
                <name>Andreas Gutheil</name>
                <email>andreas.gutheil@namics.com</email>
            </person>
        </team>
    </contact>
    <schedule>
        <!-- Entweder ical-Feed angeben oder Meetings manuell eintragen -->
        <!-- ical> https://www.google.com/calendar/ical/q408a75de70rb2ebqka3i18nc0%40group.calendar.google.com/public/basic.ics
            </ical -->
        <meeting>
            <time>2013-04-23T19:30:00</time>
            <name>#1 - Erstes Treffen der HUG Rhein-Main</name>
            <url>http://www.meetup.com/HUG-Rhein-Main/events/112847132/</url>
            <location>
                <name>TBD</name>
                <city>Mainz</city>
            </location>
        </meeting>
    </schedule>
</usergroup>
