=== rheinmainrocks/ugrm-data/xsd/usergroup.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="usergroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string">
					<xs:annotation>
						<xs:documentation>Vollständiger Name der Usergroup in Langfassung,
							z.B. Python UserGroup RheinMain
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="nickname" type="xs:string">
					<xs:annotation>
						<xs:documentation>Kurzform des Usergroup-Namens, z.B. PyUGRM
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="description" type="xs:string">
					<xs:annotation>
						<xs:documentation>Eine Beschreibung der Usergroup. Kann gerne
							ausführlich sein.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="url" type="xs:anyURI">
					<xs:annotation>
						<xs:documentation>Die URL der Homepage der Usergroup.
						</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="contact">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="mailinglist" minOccurs="0"
								maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="url" type="xs:anyURI"></xs:element>
										<xs:element name="label" type="xs:string"></xs:element>
										<xs:element name="description" type="xs:string"
											minOccurs="0"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="twitter" minOccurs="0" type="twitter"></xs:element>
							<xs:element name="hashtag" minOccurs="0" type="hashtag"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ical" minOccurs="0" type="xs:anyURI"></xs:element>
				<xs:element name="schedule">
					<xs:complexType>
						<xs:annotation>
							<xs:documentation>Liefert Information zu den nächsten Treffen der
								UserGroup. Entweder kann die URL zu einem iCal-Feed angegeben
								werden, oder die Meetings werden manuell konfiguriert.
							</xs:documentation>
						</xs:annotation>
						<xs:choice>
							<xs:element name="ical" type="xs:anyURI"></xs:element>
							<xs:element name="meeting" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:dateTime"></xs:element>
										<xs:element name="location" type="xs:string"></xs:element>
										<xs:element name="description" type="xs:string"
											minOccurs="0"></xs:element>
										<xs:element name="publictransport" type="xs:string"
											minOccurs="0"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="tags">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="tag" type="xs:token" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="photocredits" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="logo" type="xs:string" minOccurs="0"></xs:element>
							<xs:element name="group" type="xs:string" minOccurs="0"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="sponsors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="sponsor" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string"></xs:element>
										<xs:element name="url" type="xs:anyURI"></xs:element>
										<xs:element name="city" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="meetings" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Links zu den Infoseiten oder Protokollen
							vergangener Treffen.
						</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="meeting" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:date"></xs:element>
										<xs:element name="url" type="xs:anyURI"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="twitter">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentype für Twitter-Handles
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="@[a-zA-Z0-9_]{1,15}"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="hashtag">
		<xs:annotation>
			<xs:documentation>Definiert einen Datentype für Hashtags
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="#[a-zA-Z0-9]+"></xs:pattern>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== rheinmainrocks/ugrm-data/usergroup/skrm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Softwerkskammer Rhein-Main</name>
    <nickname>SWKRM</nickname>
    <description>Wir sind eine Gruppe von Softwareentwicklern, die professionell Software entwickeln möchten. 
	Dazu tauschen wir Erfahrungen zu Themen wie Clean Code, Behaviour Driven Design, Test Driven Development, Objekt-Orientiertem Design, Softwarearchitektur aber auch zu den sog. &quot;Soft Skills&quot; und den oft vernachlässigten menschlichen Aspekten der Softwareentwicklung in einem Team. 
	Wir treffen uns durchschnittlich einmal im Monat wobei das stets wechselnde Rahmenthema für ein Treffen beim vorherigen Treffen festgelegt werden.</description>
    <url>http://www.softwerkskammer.de/wiki/SoftwerkskammerFfm</url>
    <tags>
        <tag>Software Craftsmanship</tag>
        <tag>Clean Code</tag>
        <tag>Agile</tag>
    </tags>
    <contact>
        <twitter>@softwerkskammer</twitter>
        <hashtag>#swkrm</hashtag>
    </contact>
    <schedule>
        <meeting>
            <time>2013-03-25T19:00:00+01:00</time>
            <name>Treffen #16</name>
            <location>
                <name>OFfenraum coworking space</name>
                <description>Der OFfenraum ist der erste unabhängige, inhabergeführte Coworking Space in Offenbach am
                    Main.
                </description>
                <url>http://offenraum.de/#lage</url>
                <twitter>@OFfenraum</twitter>
                <publictransport>Regionalbahn HBf Offenbach. S1, S2, S8,
                    S9 Offenbach Markplatz. Bus 104 Haydnstraße.
                </publictransport>
                <street>Senefelderstr. 63</street>
                <zip>63069</zip>
                <city>Offenbach am Main</city>
            </location>
        </meeting>
        <meeting>
            <time>2013-02-25T19:00:00+01:00</time>
            <name>Treffen #15</name>
            <location>
                <name>Die Zentrale</name>
                <description>Coworking in Frankfurt. Echt jetzt. Nein, wirklich. Wir sind kein Business
                    Center. Wir haben nicht nur Schreibtische und Wlan zu vermieten.
                </description>
                <url>http://www.die-zentrale-ffm.de/#section-n6</url>
                <twitter>@zentrale_ffm</twitter>
                <publictransport>U4, Tram 12, Bus 34 Bornheim Mitte</publictransport>
                <street>Berger Straße 175</street>
                <zip>60385</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
    </schedule>
    <photocredits>
        <group>Foto: [Markus Tacker](http://tckr.cc/).</group>
    </photocredits>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/jugda.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
  <name>Java User Group Darmstadt</name>
  <nickname>JUGDA</nickname>
  <description>Die JUG DA ist eine offene Non-Profit-Community mit dem Ziel
		sich über aktuelle Themen zur Anwendung von Java Technologie
		auszutauschen – und darüber hinaus einen Blick auf andere (VM-) Sprachen
		und Technologien wie JavaScript, Closure, oder Maven zu werfen.
    </description>
  <url>http://www.jug-da.de</url>
  <tags>
    <tag>Java</tag>
    <tag>JavaScript</tag>
    <tag>Spring</tag>
  </tags>
  <contact>
    <mailinglist>
      <url>http://groups.google.com/group/jug-da</url>
      <label>Mailingliste</label>
      <description>Termine und News</description>
    </mailinglist>
    <twitter>@JUG_DA</twitter>
  </contact>
  <schedule>
    <ical>https://www.google.com/calendar/ical/q5vt4sq9qt7i8bjsdfgshg4b94%40group.calendar.google.com/public/basic.ics</ical>
  </schedule>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/gdgrm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Google Developer Group Rhein-Main</name>
    <nickname>GDGRM</nickname>
    <description>Everything Google.</description>
    <url>http://gdgrm.org</url>
    <tags>
        <tag>Google Technologien</tag>
    </tags>
    <contact>
        <mailinglist>
            <url>https://sites.google.com/site/gdgrheinmain/get-in-contact/anmeldung-zur-mailinglist</url>
            <label>Mailingliste</label>
        </mailinglist>
        <twitter>@gdgrheinmain</twitter>
    </contact>
    <schedule>
        <meeting>
            <time>2013-03-01T19:00:00+01:00</time>
            <name>GDG RheinMain Stammtisch Februar 2013</name>
            <url>https://plus.google.com/u/0/events/cj6qaa8m2df9gvmv1v6bp5g43t0</url>
            <location>
                <name>SRZ Gastro</name>
                <url>https://plus.google.com/105879634205744206011/about?hl=de</url>
                <street>Rotfeder-Ring 13</street>
                <zip>60327</zip>
                <city>Frankfurt</city>
            </location>
        </meeting>
    </schedule>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/jugf.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Java User Group Frankfurt</name>
    <nickname>JUGF</nickname>
    <description>Die Java User Group Frankfurt ist ein lokaler Verbund von Entwicklern, die sich für Themen rund um die
        Programmiersprache Java interessieren. Schwerpunkte der User Group sind die Themen Enterprise Applications mit
        dem Spring Framework, Skriptsprachen auf der JVM: Groovy &amp; Scala,
        Fast Prototyping &amp; Cloud Computing: Grails, Google App Engine &amp; Co.
        Wir versuchen, in regelmäßigen Treffen Informationen rund um diese Themen in lockerer Atmosphäre auszutauschen.
        Nach Möglichkeit soll für jedes Treffen ein Thema festgelegt werden, über welches ein oder mehrere Teilnehmer
        referieren.
    </description>
    <url>http://www.jugf.de</url>
    <tags>
        <tag>Java</tag>
        <tag>Groovy</tag>
        <tag>Spring</tag>
    </tags>
    <contact>
        <mailinglist>
            <url>https://groups.google.com/forum/?hl=en&amp;fromgroups#!forum/jugf-java-user-group-frankfurt</url>
            <label>Mailingliste</label>
        </mailinglist>
        <twitter>@jugffm</twitter>
        <googleplus>https://plus.google.com/u/0/communities/116872166355404683062</googleplus>
        <xing>https://www.xing.com/net/pria6135dx/jugf/</xing>
    </contact>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/ceph.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Ceph Frankfurt</name>
    <description>This is a group for anyone interested in [Ceph](http://ceph.com/). All skills levels are welcome. There
        is a growing user community around this Free Software distributed storage. Participants are expected to share
        their use cases, tips and tricks, projects, have a good time in a friendly and informal atmosphere.
    </description>
    <url>http://www.meetup.com/Ceph-Frankfurt/</url>
    <tags>
        <tag>Ceph</tag>
        <tag>Distributed storage</tag>
        <tag>Cloud</tag>
    </tags>
    <schedule>
        <meeting>
            <time>2014-02-26T19:00:00+01:00</time>
            <name>Drink and talk before the Ceph day</name>
            <description>Inktank organizes the [Ceph day February
                27th](http://www.eventbrite.com/e/ceph-day-frankfurt-tickets-10173269523). Let's take this opportunity
                to meet and discuss Ceph the evening before.
            </description>
            <url>http://www.meetup.com/Ceph-Frankfurt/events/164620852/</url>
        </meeting>
    </schedule>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/rugrm.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Rails- und Ruby-Usergroup Rhein-Main</name>
    <nickname>rugrm</nickname>
    <description>Wir treffen uns einmal pro Monat, um gemeinsam Ã¼ber aktuelle Themen in der Web-Entwicklung zu sprechen und Erfahrungen auszutauschen.</description>
    <url>http://rugrm.tumblr.com/</url>
    <tags>
        <tag>Rails</tag>
        <tag>Ruby</tag>
    </tags>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/schnitzelof.xml
<?xml version="1.0" encoding="UTF-8" ?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd" female="false">
    <name>#SchnitzelOF</name>
    <description>Gemütliches Beisammensein bei Schnitzel. Frankfurter sind natürlich Willkommen!</description>
    <url>http://usergroups.rheinmainrocks.de/~schnitzelof</url>
    <tags>
        <tag>Schnitzel</tag>
        <tag>Offenbach</tag>
    </tags>
    <contact>
        <twitter>@SchnitzelOF</twitter>
        <hashtag>#SchnitzelOF</hashtag>
    </contact>
    <schedule>
        <meeting>
            <time>2013-08-16T19:00:00+02:00</time>
            <name>#SchnitzelOF August 2013</name>
            <location>
                <name>Hessewirtschaft</name>
                <url>http://hessewirtschaft.de/Offenbach/</url>
                <foursquare>https://de.foursquare.com/v/hessewirtschaft/4baba519f964a52054bc3ae3</foursquare>
                <street>Senefelderstr. 100</street>
                <zip>63069</zip>
                <city>Offenbach</city>
            </location>
        </meeting>
    </schedule>
    <photocredits>
        <group>Foto: [@xaeron](https://twitter.com/xaeron)</group>
    </photocredits>
</usergroup>

=== rheinmainrocks/ugrm-data/usergroup/tpostmtshoff.xml
<?xml version="1.0" encoding="UTF-8"?>
<usergroup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/usergroup.xsd">
    <name>Typostammtisch Offenbach</name>
    <nickname>tpostmtshoff</nickname>
    <description>Seit 2004 treffen sich einmal im Monat Typografie- und Schriftbegeisterte in Offenbach.</description>
    <url>https://www.facebook.com/pages/Typostammtisch-Offenbach/348203441925830</url>
    <tags>
        <tag>Typografie</tag>
    </tags>
    <contact>
        <twitter>@typo_stammtisch</twitter>
    </contact>
    <schedule>
        <meeting>
            <time>2013-02-05T20:00:00+01:00</time>
            <description>Typostammtisch</description>
            <location>
                <name>Weinstube Offenbach</name>
                <url>http://www.die-weinstube.eu/</url>
                <twitter>@die_weinstube</twitter>
                <street>Taunusstra√üe 19</street>
                <zip>63067</zip>
                <city>Offenbach</city>
            </location>
        </meeting>
    </schedule>
    <photocredits>
        <logo>Logo: [Facebook](https://www.facebook.com/media/set/?set=a.348205621925612.79305.348203441925830&amp;type=3)</logo>
        <group>Foto: [Facebook](https://www.facebook.com/photo.php?fbid=348207005258807&amp;set=pb.348203441925830.-2207520000.1360061532&amp;type=3&amp;theater)</group>
    </photocredits>
</usergroup>
